fn main() {
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=icons/32x32.png");
    println!("cargo:rerun-if-changed=icons/128x128.png");
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_settings",
            "get_overlay_settings",
            "save_settings",
            "set_groq_api_key",
            "clear_groq_api_key",
            "get_devices",
            "start_recording",
            "stop_recording",
            "record_mic_test",
            "set_overlay_geometry",
            "get_model_manifest",
            "download_model",
            "cancel_download",
            "validate_model",
            "check_installed_models",
            "history_list",
            "history_get",
            "history_delete",
            "history_clear",
            "history_export",
            "vocabulary_list",
            "vocabulary_upsert",
            "vocabulary_delete",
            "vocabulary_import_csv",
            "stats_summary",
            "export_config",
            "import_config",
            "apply_import",
        ]),
    ))
    .expect("failed to build Tauri application")
}
